//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringFort {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineeringFort.DisplayStrings", typeof(DisplayStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable Bending Stress.
        /// </summary>
        public static string AllowableBendingStress {
            get {
                return ResourceManager.GetString("AllowableBendingStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam.
        /// </summary>
        public static string Beam {
            get {
                return ResourceManager.GetString("Beam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bending Stress Check.
        /// </summary>
        public static string BendingStressCheck {
            get {
                return ResourceManager.GetString("BendingStressCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Status.
        /// </summary>
        public static string CheckStatus {
            get {
                return ResourceManager.GetString("CheckStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Section.
        /// </summary>
        public static string CrossSection {
            get {
                return ResourceManager.GetString("CrossSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elastic Modulus.
        /// </summary>
        public static string ElasticModulus {
            get {
                return ResourceManager.GetString("ElasticModulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork.
        /// </summary>
        public static string Formwork {
            get {
                return ResourceManager.GetString("Formwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Component.
        /// </summary>
        public static string FormworkComponent {
            get {
                return ResourceManager.GetString("FormworkComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Layer Check.
        /// </summary>
        public static string FormworkLayerCheck {
            get {
                return ResourceManager.GetString("FormworkLayerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Sheathing.
        /// </summary>
        public static string FormworkSheathing {
            get {
                return ResourceManager.GetString("FormworkSheathing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Sheathing Layer Check.
        /// </summary>
        public static string FormworkSheathingLayerCheck {
            get {
                return ResourceManager.GetString("FormworkSheathingLayerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Support.
        /// </summary>
        public static string FormworkSupport {
            get {
                return ResourceManager.GetString("FormworkSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Support Layer Check.
        /// </summary>
        public static string FormworkSupportLayerCheck {
            get {
                return ResourceManager.GetString("FormworkSupportLayerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formwork Tie Rod.
        /// </summary>
        public static string FormworkTieRod {
            get {
                return ResourceManager.GetString("FormworkTieRod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Valid.
        /// </summary>
        public static string IsValid {
            get {
                return ResourceManager.GetString("IsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Bending Moment.
        /// </summary>
        public static string MaximumBendingMoment {
            get {
                return ResourceManager.GetString("MaximumBendingMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Bending Stress.
        /// </summary>
        public static string MaximumBendingStress {
            get {
                return ResourceManager.GetString("MaximumBendingStress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Deflection.
        /// </summary>
        public static string MaximumDeflection {
            get {
                return ResourceManager.GetString("MaximumDeflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Side Pressure.
        /// </summary>
        public static string MaximumSidePressure {
            get {
                return ResourceManager.GetString("MaximumSidePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Check.
        /// </summary>
        public static string QuantityCheck {
            get {
                return ResourceManager.GetString("QuantityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Formwork Design.
        /// </summary>
        public static string SideFormworkDesign {
            get {
                return ResourceManager.GetString("SideFormworkDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab.
        /// </summary>
        public static string Slab {
            get {
                return ResourceManager.GetString("Slab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Checks.
        /// </summary>
        public static string SubChecks {
            get {
                return ResourceManager.GetString("SubChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Spacing.
        /// </summary>
        public static string SupportSpacing {
            get {
                return ResourceManager.GetString("SupportSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tributary Width.
        /// </summary>
        public static string TributaryWidth {
            get {
                return ResourceManager.GetString("TributaryWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniformly Distributed Load.
        /// </summary>
        public static string UniformlyDistributedLoad {
            get {
                return ResourceManager.GetString("UniformlyDistributedLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Strip Moment Of Inertia.
        /// </summary>
        public static string UnitStripMomentOfInertia {
            get {
                return ResourceManager.GetString("UnitStripMomentOfInertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Strip Section Modulus.
        /// </summary>
        public static string UnitStripSectionModulus {
            get {
                return ResourceManager.GetString("UnitStripSectionModulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Strip Width.
        /// </summary>
        public static string UnitStripWidth {
            get {
                return ResourceManager.GetString("UnitStripWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
